seed: 42
device: 'cuda:0'
batch_size: 32
epochs: 200
wandb: False
data_dir: './data/one_fnosystem/'
x_mode: All # Initial
batch_size: 64
test_size: 0.2
normalize: True
skip_connection: False
same_system: True

loss_params:
  regression_loss: 
    loss: 'Lploss'
    reduction: 'sum'
  label_loss:
    loss: 'Lploss'
    weight: 0.9
  reduction: 'mean'


optimizer: 'Adam'
optimizer_params:
  lr: 0.001
  weight_decay: 0.0001

scheduler: 'ReduceLROnPlateau'
scheduler_params:
  mode: 'min'
  factor: 0.1
  patience: 5
  threshold: 0.0001
  threshold_mode: 'rel'
  cooldown: 0
  min_lr: 0
  eps: 1e-08

early_stopping: True
early_stopping_params:
  patience: 20
  min_delta: 0.0001
  mode: 'min'
  monitor: 'val_loss'
  verbose: False

identification_model: LSTM
identification_model_params:
  hidden_size: 64
  num_layers: 2
  dropout_rate: 0
  activation: 'ReLU'
  norm_type: 'LayerNorm'
  seq2seq: False  # If True, the model is encoder-decoder, else it is encoder-only
  bidirectional: False


# identification_model: 'MLP' # RNN LSTM GRU
# identification_model_params:
#   num_blocks: 2
#   block_layers: [2, 2]
#   hidden_size: [[64, 128],[128, 128]]
#   dropout_rate: 0
#   activation: 'ReLU'
#   norm_type: 'BatchNorm'
#   use_residual: False

# AParam_model: 'MLP'
# AParam_model_params:
#   num_blocks: 2
#   block_layers: [2, 2]
#   hidden_size: [[64, 128],[128, 128]]
#   output_size: 5
#   dropout_rate: 0.2
#   activation: 'ReLU'
#   norm_type: 'BatchNorm'
#   use_residual: False
#   use_U: False

AParam_model: 'Embedding'
AParam_model_params:
  hidden_size: 64
  output_size: 5
  dropout_rate: 0
  activation: 'ReLU'
  norm_type: 'LayerNorm'
  use_residual: False
  use_x: True

GParam_model:  LSTM # GRU, RNN, Transformer
GParam_model_params:
  hidden_size: 64
  num_layers: 2
  dropout_rate: 0
  activation: 'ReLU'
  norm_type: 'LayerNorm'
  seq2seq: False  # If True, the model is encoder-decoder, else it is encoder-only
  bidirectional: False

FINAL_model_params:
  QRB_size: 3
  hidden_size: 64
  dropout_rate: 0
  activation: 'ReLU'
  norm_type: 'LayerNorm'
  use_residual: False
  
  

